What is the Capital of {stateOrCountry}? Respond with the following format:
           The capital of ```stateOrCountry``` is ```capital```.
           The city has a population of ```population```.
           The city is located in ```region```.
           The priamry language spoken is ```language```.
           The sex ratio of this city is ``` sex ratio```.
           The currency used is ```currency```.
           The city is famous for ```famous```.